### ISSUE TITLE
Part of inputfield disappearing while typing

### ISSUE THREAD

**Issue by markmooibroek** [henrychavez/materialize-tags#17]
If I try to type Amsterdam as a first entry. The first part of the word will disappear. Im guessing the `size` attribute isn't correctly set.

<img width="165" alt="screen shot 2016-01-02 at 06 36 00" src="https://cloud.githubusercontent.com/assets/1412238/12073340/9e6ce9a2-b11b-11e5-9fdb-a6b7ccb11fa6.png">
<img width="126" alt="screen shot 2016-01-02 at 06 36 17" src="https://cloud.githubusercontent.com/assets/1412238/12073339/9e6b4980-b11b-11e5-9326-d9ad37542d9d.png">
<img width="122" alt="screen shot 2016-01-02 at 06 36 21" src="https://cloud.githubusercontent.com/assets/1412238/12073338/9e68192c-b11b-11e5-9c9b-4d4831d52bd5.png">

**Comment by DEKHTIARJonathan** [comment]
Still a problem @markmooibroek ?

**Comment by greenlion** [comment]
Yes

**Comment by DEKHTIARJonathan** [comment]
@greenlion, can you please check the version you are using ?
https://github.com/henrychavez/materialize-tags/releases 

It needs to be v1.1.0

Do you have the problem on the demo page (http://henrychavez.github.io/materialize-tags/examples/) ? Because, I can't manage to reproduce.

Please make a https://jsfiddle.net/ to show your problem.

Regards,

Jonathan DEKHTIAR

**Comment by greenlion** [comment]
Oh, I had an older copy. I'll test latest version.  Sorry for the confusion.  Peace.
